/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/x327PSQIkEg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div
      className="flex flex-col h-[90vh] max-h-[90vh] bg-gray-100 dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
      <header
        className="flex items-center px-4 py-3 bg-gray-900 dark:bg-gray-950 text-white">
        <div className="flex items-center space-x-3">
          <Avatar>
            <AvatarImage alt="Chatbot" src="/chatbot-avatar.png" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
          <h2 className="text-lg font-medium">Chatbot</h2>
        </div>
      </header>
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        <div className="flex items-start space-x-3">
          <Avatar>
            <AvatarImage alt="Chatbot" src="/chatbot-avatar.png" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
          <div
            className="bg-white dark:bg-gray-950 dark:text-gray-200 rounded-lg p-3 max-w-[70%]">
            <p>Hello! How can I assist you today?</p>
          </div>
        </div>
        <div className="flex items-start space-x-3 justify-end">
          <div className="bg-blue-500 text-white rounded-lg p-3 max-w-[70%]">
            <p>Hi there! I have a few questions about your product.</p>
          </div>
          <Avatar>
            <AvatarImage alt="User" src="/user-avatar.png" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
        </div>
      </div>
      <div
        className="bg-gray-100 dark:bg-gray-950 px-4 py-3 flex items-center space-x-2">
        <Input className="flex-1" placeholder="Type your message..." type="text" />
        <Button>Send</Button>
      </div>
    </div>)
  );
}
